In [ ]:
import pandas as pd
import sqlite3

conn = sqlite3.connect('music.sqlite') # Connect
cur = conn.cursor() # Create cursor
cur.execute('DROP TABLE IF EXISTS Tracks') # Execute: DROP & CREATE TABLE
cur.execute('CREATE TABLE Tracks (title TEXT, plays INTEGER)')
conn.close() # Close

conn = sqlite3.connect('music.sqlite') # Connect 
cur = conn.cursor() # Create cursor
cur.execute('INSERT INTO Tracks (title, plays) VALUES (?, ?)', # Execute: INSERT
    ('Thunderstruck', 20))
cur.execute('INSERT INTO Tracks (title, plays) VALUES (?, ?)',
    ('My Way', 15))
conn.commit()

conn = sqlite3.connect('music.sqlite') # Connect 
df = pd.read_sql('SELECT * FROM Tracks', conn) # Read values
conn.close()
df.head()